spring:
  profiles:
    active: local
  application:
    name: gitlab-release-server

# 服务端口，将默认为5050.
server:
  port: 5050

# 日志相关的简单配置.
logging:
  file: logs/gitlab-release-server.log
  level:
    root: info
    org:
      apache: warn
      springframework: warn

# Minio的配置，这是一个用于开发测试的 minio 地址.
minio:
  endpoint: http://172.25.16.76:9000
  access-key: dev
  secret-key: 123456789
  bucket: releases

# 本系统的相关配置项.
system:
  baseUrl: http://127.0.0.1:5050